<template>
  <div class="row">
    <div class="col-4">
      <nav id="navbar-example3" class="h-100 flex-column align-items-stretch pe-4 border-end">
        <nav class="nav nav-pills flex-column">
          <a class="nav-link" href="#item-1">Item 1</a>
          <nav class="nav nav-pills flex-column">
            <a class="nav-link ms-3 my-1" href="#item-1-1">Item 1-1</a>
            <a class="nav-link ms-3 my-1" href="#item-1-2">Item 1-2</a>
          </nav>
          <a class="nav-link" href="#item-2">Item 2</a>
          <a class="nav-link" href="#item-3">Item 3</a>
          <nav class="nav nav-pills flex-column">
            <a class="nav-link ms-3 my-1" href="#item-3-1">Item 3-1</a>
            <a class="nav-link ms-3 my-1" href="#item-3-2">Item 3-2</a>
          </nav>
        </nav>
      </nav>
    </div>

    <div class="col-8">
      <div data-bs-spy="scroll" data-bs-target="#navbar-example3" data-bs-smooth-scroll="true" class="scrollspy-example-2" tabindex="0">
        <div id="item-1">
          <h4>Item 1</h4>
          <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae commodi distinctio, et itaque minima quibusdam quidem rem saepe sapiente? Asperiores consequuntur dolores ea labore maxime minima odio optio similique veritatis?</span><span>Aliquam animi autem dolor, dolorem, est facilis id incidunt laboriosam laborum, maxime natus quae similique temporibus veritatis voluptatibus. Dolore dolorum saepe voluptates! Asperiores distinctio dolorem doloremque laborum maiores porro quos.</span><span>Inventore laudantium maxime praesentium qui. Consectetur ea illum impedit ipsam maiores neque odio quam sit unde veritatis. Facilis molestias, quibusdam. Asperiores dignissimos ducimus illum in molestias provident quasi quo tenetur?</span><span>Aut est ipsum minus officia quibusdam quisquam tempora. Accusamus, dignissimos esse iste neque non quidem. Corporis culpa deleniti eos inventore, magnam, magni maiores natus neque omnis possimus quo repellendus reprehenderit?</span><span>Architecto consequatur delectus deserunt illo non quos sit! Aliquam dolor dolorem ea est harum inventore iste natus possimus quaerat quidem quisquam repellendus, saepe soluta sunt ut! Beatae perspiciatis quisquam ullam!</span><span>Amet aperiam asperiores consequatur dolorem fugiat laudantium minus necessitatibus nostrum omnis perferendis provident, quas, quis repellat repellendus sint soluta suscipit. Accusamus, beatae commodi consectetur consequuntur culpa cupiditate quas quia voluptatum.</span><span>Adipisci autem, blanditiis illo ipsa libero necessitatibus nulla officiis optio placeat possimus quas ratione ullam voluptatem. Aliquam aperiam error et hic impedit ipsam iure, minus nam nemo, nobis odit omnis?</span><span>Aperiam eius eos excepturi quis veritatis! Ad aspernatur corporis dolorum enim et facilis inventore laboriosam magni necessitatibus nihil nostrum numquam, odit omnis possimus quae quasi qui ratione sunt temporibus voluptate!</span><span>Aliquid cupiditate error facere molestiae obcaecati vel. A adipisci eaque iusto odit pariatur! Aliquam delectus, dolor ea eaque id molestiae non nulla odit quaerat quasi quidem sed totam, veritatis voluptas?</span><span>Accusantium ad esse eum ipsum officiis rem sed sequi. Aliquam aspernatur deleniti dolorem earum expedita illum ipsa iure maxime necessitatibus odit officiis omnis placeat, praesentium quis quo quos repellendus unde.</span></p>
        </div>
        <div id="item-1-1">
          <h5>Item 1-1</h5>
          <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque blanditiis maiores maxime. Consequatur cupiditate dolor facere impedit inventore laborum nihil nulla officiis optio provident quae quo sed, vitae. Obcaecati, sapiente!</span><span>Ad alias aliquam animi corporis dolorem ea eligendi eveniet excepturi exercitationem fugit, in, incidunt inventore libero officia officiis reiciendis similique soluta, voluptatum! Ipsa maxime sed sint? Assumenda earum eligendi vel!</span><span>Ab ad aperiam aspernatur beatae corporis cum cupiditate doloremque eligendi enim, esse exercitationem facilis libero magnam maiores modi molestias officia omnis quam quibusdam unde ut vel veritatis vitae voluptatem voluptatibus?</span><span>Commodi fuga fugiat nulla quaerat quam quibusdam repellendus sequi velit. Ab blanditiis consequatur dolorem dolorum ducimus ex fuga, fugiat inventore, magni minima nam nobis non nulla sed, velit veniam voluptas.</span><span>Eaque eveniet exercitationem hic officiis qui. Asperiores aspernatur assumenda debitis, eligendi error fugiat ipsa maiores modi molestiae nam nemo omnis quis ratione recusandae, repellendus repudiandae tempore ullam vel veritatis, voluptatibus!</span><span>Beatae consequuntur explicabo fugit numquam obcaecati tempore voluptatum! Aliquid animi, commodi debitis delectus ea eos exercitationem explicabo id in itaque magni maxime nisi provident quasi quidem rem sint tenetur voluptatem?</span><span>Accusamus animi, autem cum distinctio eius esse ipsum iusto natus nemo pariatur placeat praesentium quod rem rerum, sapiente sint ullam unde vero. Accusantium aperiam autem, expedita fugiat id modi rem!</span><span>Ad animi debitis deleniti earum eveniet, fugit incidunt ipsa itaque magnam maxime minus molestias nam perferendis quae, quidem quisquam quod rem sed soluta unde vel velit vero. Atque, ea reiciendis?</span><span>Cupiditate, ex, sit. Dolor dolores est labore laudantium nihil nulla optio ratione sapiente unde. Aspernatur, assumenda corporis delectus explicabo impedit ipsam magni maiores, porro, quam quasi quisquam reiciendis similique veritatis.</span><span>Accusamus amet aperiam assumenda culpa dicta doloremque dolores eius eum eveniet facilis modi nihil non obcaecati odio odit pariatur, quas, rem repudiandae sit sunt totam unde ut vel veniam, vero?</span></p>
        </div>
        <div id="item-1-2">
          <h5>Item 1-2</h5>
          <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti dolores eaque esse eum, expedita explicabo repellat voluptate? Ipsum nisi placeat quibusdam repudiandae voluptatem. Maiores natus nulla pariatur quam repellat soluta.</span><span>Ad deserunt doloribus modi! Ad consequatur eum iure nam optio perferendis provident quis reiciendis repellat, sint? Aliquam et eum fugiat necessitatibus non porro ratione veniam. Consectetur dignissimos illo rerum sint?</span><span>Modi, non quasi quibusdam quidem quo repellendus sint suscipit! Beatae, deleniti dicta esse explicabo facere inventore ipsa labore porro quidem ratione repudiandae similique, temporibus voluptates. Aut fuga maxime saepe sint!</span><span>Adipisci consequatur et nam possimus praesentium quibusdam quidem ratione sequi suscipit voluptatum. Autem dolor dolores doloribus itaque iure sequi tempore. Ab atque autem dolores eius enim expedita hic neque possimus?</span><span>Ad aliquid amet asperiores, blanditiis dolore dolorum eveniet facere fuga harum inventore laboriosam libero nesciunt nihil obcaecati odio perferendis, provident quia quibusdam quis quo repellendus rerum ut vitae voluptas voluptatum.</span><span>Aliquid animi aperiam cumque debitis exercitationem expedita facilis fuga illo in ipsa magnam, minima nihil, nobis, quisquam repudiandae sed sint veniam vitae. Alias, dicta eum minus odio quasi quidem totam?</span><span>Aspernatur autem commodi consectetur dignissimos eaque esse ex excepturi explicabo fugiat id iste, itaque, libero molestiae reiciendis sit voluptas, voluptatem? A earum minus repellat rerum sed sit. Nemo, repudiandae, voluptatibus!</span><span>Ad aspernatur dolore ipsum iste, magnam praesentium sequi voluptas! Accusantium aspernatur assumenda atque cupiditate debitis nisi odit quia vitae! Accusantium amet beatae eum iste natus nulla qui, repellendus sequi unde!</span><span>Ad blanditiis dolores fugiat inventore. Blanditiis quisquam rem similique unde vel? Deleniti deserunt dolores veniam. Architecto, cupiditate dolore esse excepturi fuga harum impedit ipsam, magnam maiores nihil, quidem vitae voluptas.</span><span>Adipisci architecto aut commodi fugit ratione repudiandae veritatis? Ad aliquam aliquid atque commodi corporis, dolor, error facere iste itaque iusto libero modi nam natus nobis nulla officiis, provident similique totam!</span></p>
        </div>
        <div id="item-2">
          <h4>Item 2</h4>
          <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus distinctio enim esse perspiciatis voluptatum! Accusantium atque blanditiis, cumque debitis est illum magni, maiores molestias optio quam quos rerum sapiente soluta?</span><span>A accusantium adipisci animi asperiores aspernatur blanditiis consectetur, consequuntur corporis debitis doloremque facilis ipsam molestiae neque nihil nisi officiis perspiciatis possimus provident, recusandae sequi similique soluta suscipit tempore totam velit.</span><span>Asperiores aspernatur cum, doloribus eius eos et eum expedita impedit ipsum iusto obcaecati officia optio perferendis porro quo reiciendis repellat reprehenderit rerum similique soluta sunt unde velit. Amet, id, possimus.</span><span>Blanditiis delectus deserunt dolorem ex expedita ipsam, ipsum iure, laboriosam laborum magnam, magni neque repellendus similique? Aliquid amet cum ea illo impedit, magni, odit officia omnis possimus quae sit, tempora.</span><span>Aliquid enim fugiat quas. Accusamus aliquid atque autem doloremque dolorum ea eligendi, ex excepturi ipsa laborum molestias nulla perferendis quaerat, quas quasi repudiandae sint soluta tenetur unde veniam vero voluptate?</span><span>Ab, accusamus culpa deserunt eum expedita impedit in maxime natus odit, qui quos repellendus rerum vel? Asperiores, consectetur consequuntur deserunt distinctio dolor ea esse facilis, in quasi quo quos reiciendis?</span><span>A beatae blanditiis consectetur cupiditate deleniti fugit ipsam iure laudantium libero maxime minus molestias nemo numquam obcaecati odio qui ratione repudiandae rerum sed sint sit suscipit tempore unde, ut voluptas?</span><span>Cumque cupiditate dolorem, enim quaerat quasi unde vel veniam. Amet assumenda aut commodi dignissimos distinctio dolores exercitationem explicabo iusto laboriosam laudantium maiores, nisi omnis praesentium quis sapiente sed temporibus vero.</span><span>Alias aliquid autem hic impedit maxime nisi porro possimus qui recusandae sint sunt, veniam, voluptas? Doloribus libero nam quia quisquam quod recusandae repudiandae saepe tempore totam, voluptatem. Consequuntur, fuga vitae?</span><span>Ab aperiam aspernatur dolor exercitationem fugit illo magnam officia placeat quaerat repellendus. Consectetur distinctio dolore ducimus esse iure labore laborum molestiae natus nobis non perspiciatis, porro repudiandae suscipit velit vitae.</span></p>
        </div>
        <div id="item-3">
          <h4>Item 3</h4>
          <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad asperiores deserunt et obcaecati placeat similique totam? Aperiam architecto esse expedita laboriosam natus quae, quis vero. Eaque error laudantium nihil tempore.</span><span>Aperiam, dolorum eveniet fuga, fugiat laboriosam minima nesciunt omnis porro quod repellendus saepe sed totam veritatis voluptatem voluptatum! Delectus dolor fugiat, minus porro suscipit voluptatum? Culpa distinctio eius itaque qui!</span><span>Ab amet, animi, assumenda dicta eaque impedit iusto maiores nulla, quod sequi tempora ullam? Adipisci alias consequatur cupiditate earum et, exercitationem hic iure minus nesciunt non omnis quidem reprehenderit sunt?</span><span>Ab commodi dicta distinctio dolores, ea, in libero molestiae nam nihil possimus quaerat qui quod saepe, sequi similique suscipit tempore. Aperiam cumque debitis dolorum iure libero, necessitatibus ratione! Nemo, veniam?</span><span>Eaque explicabo id laudantium magnam neque perspiciatis quis reiciendis, suscipit? Ad animi aut cum enim expedita incidunt, quae voluptate? Amet architecto commodi dicta enim illum in necessitatibus, odit voluptates. Ad.</span><span>Aut corporis cupiditate debitis dicta dolor dolore doloribus enim esse exercitationem fuga incidunt iure labore laborum, laudantium, libero magni natus obcaecati placeat quae quam qui reiciendis saepe vel, velit voluptatibus?</span><span>Accusantium aliquid consequuntur, doloribus ipsum labore magnam maxime quaerat quia sequi similique totam vel veritatis? Commodi iste modi nam officiis quia? Distinctio earum est officiis pariatur praesentium, quod vel veniam.</span><span>Consectetur distinctio eos error est iusto? Aperiam aut beatae eaque harum illum ipsum laudantium magni, nisi quibusdam quidem quis suscipit ullam, veniam veritatis vero? Consequatur culpa fuga id mollitia perferendis?</span><span>Animi architecto culpa cupiditate, dolorum ducimus excepturi ipsa ipsum iste, iure labore mollitia, nam nesciunt nisi odit quisquam quod rerum sed sequi suscipit veniam! Doloribus explicabo id placeat vel voluptas?</span><span>Aliquid aut, cum deserunt dicta, dolores eos id maiores nesciunt nulla odio quasi quod repudiandae sequi sint voluptatem! Dicta ducimus illo saepe sunt. Ad deleniti quos sed unde. Libero, nihil.</span></p>
        </div>
        <div id="item-3-1">
          <h5>Item 3-1</h5>
          <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae corporis dolorem iure perspiciatis repudiandae, unde veritatis! A amet, dicta ea laudantium, molestiae natus neque optio perferendis quisquam suscipit tempore voluptatum?</span><span>Facilis similique, soluta? A atque culpa delectus deserunt eligendi error inventore nobis quia quis repudiandae? Ab beatae blanditiis fugit magnam odit pariatur perferendis quas quos vel. Dolorum omnis quisquam sunt?</span><span>Accusamus, accusantium alias atque dolores, eius est ex excepturi illo impedit, ipsam laborum mollitia nisi non omnis praesentium reiciendis sapiente vel voluptatibus. Ducimus esse iste laborum laudantium quod sed tempora.</span><span>A animi aspernatur atque beatae consectetur culpa cupiditate dicta dolores eligendi, enim et exercitationem explicabo facilis fuga ipsam iure molestiae, nostrum obcaecati placeat quae quasi quo ratione rerum soluta tempore!</span><span>Asperiores dignissimos, excepturi exercitationem fuga nesciunt recusandae tempore ut velit voluptate! Atque eligendi iure necessitatibus? A aperiam consectetur, eum maiores minima placeat quae quibusdam recusandae rerum suscipit ut veritatis voluptas.</span><span>Ad aperiam autem beatae cumque cupiditate debitis deserunt distinctio dolor dolorem dolorum ducimus, eius fuga hic incidunt maxime minus odio praesentium quae quidem repellat repellendus repudiandae saepe similique soluta sunt.</span><span>Asperiores distinctio perferendis perspiciatis quidem repellendus? Aperiam cumque possimus quod sit tempora? Architecto eos eveniet harum illo molestias numquam, perferendis possimus quis ratione reprehenderit suscipit tempora voluptate. Consectetur, esse, similique?</span><span>Ad adipisci atque aut beatae delectus deleniti dolore doloremque esse impedit incidunt labore minus modi mollitia nam nihil nisi numquam odit sapiente, sequi sint sit tempore, voluptas. Minima, rem, repudiandae.</span><span>Alias aliquid animi aperiam deserunt illo ipsa, ipsam iure qui reiciendis similique sit vitae. Dolorem quae reprehenderit voluptate! Aspernatur doloremque eaque eius fugiat ipsum labore laudantium nemo optio quibusdam vel?</span><span>Aliquam aperiam, aut cumque delectus dignissimos, doloribus excepturi, exercitationem facere hic impedit incidunt maiores molestias nam natus nesciunt quam qui quia recusandae reprehenderit repudiandae sint soluta tenetur unde veniam vitae!</span></p>
        </div>
        <div id="item-3-2">
          <h5>Item 3-2</h5>
          <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut delectus earum eligendi itaque maxime nihil vitae! Ad enim inventore ipsam ipsum magnam maiores maxime, mollitia numquam, provident quasi quidem voluptatibus!</span><span>Aperiam debitis minima numquam odit quas repellat repellendus sint! A assumenda corporis eveniet maiores quisquam temporibus vel. Adipisci dignissimos dolor harum in ipsa ipsum, laudantium nobis officiis perferendis quibusdam repudiandae.</span><span>Aliquam aliquid aperiam asperiores autem beatae dicta eligendi eos error exercitationem in iusto laborum laudantium magnam necessitatibus officia officiis possimus, quas reprehenderit sed sit unde veritatis vero, voluptas? Architecto, et?</span><span>Corporis eos eum facere ipsam numquam sint sit voluptates. A aperiam, corporis ea eligendi esse ipsam iusto minima modi natus nemo nihil numquam quae, quia recusandae soluta, voluptate voluptatibus voluptatum.</span><span>Adipisci amet atque corporis cum cupiditate dicta, dolorem ducimus ex explicabo id laborum maxime minima odio odit omnis perferendis perspiciatis possimus, quaerat quas quo sapiente sed, temporibus ut velit veniam.</span><span>A accusantium alias architecto, asperiores consequuntur deleniti deserunt dicta dolorem dolores ducimus eaque, est, facilis illum molestiae nam natus non nostrum officiis optio perspiciatis quidem repellat rerum sequi sit voluptatibus!</span><span>Accusamus eveniet explicabo facere id laborum, maxime quibusdam! Accusamus alias atque autem consectetur cum delectus deleniti dolorem enim excepturi ipsam laborum necessitatibus, nemo pariatur quod, sapiente tempore tenetur vero vitae!</span><span>Adipisci atque, cumque deserunt error ipsa iste magni porro sequi! Alias, animi at cupiditate et excepturi expedita explicabo impedit labore molestiae natus nulla praesentium quidem quisquam ratione, repellendus, sapiente vel!</span><span>Cupiditate doloremque dolorum eos et laboriosam optio velit vero. Atque consequuntur eligendi eos exercitationem fugiat libero magnam, mollitia natus pariatur porro possimus quae quis quod quos recusandae rerum sequi? Ut.</span><span>Ab aliquam at autem blanditiis cum debitis delectus dignissimos dolor doloribus, error eum hic in inventore iure libero necessitatibus nostrum quibusdam recusandae rem repellendus reprehenderit rerum sed tenetur ut velit.</span></p>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "About",
  props: ['id'],
  mounted() {
    console.log(this.id)
  }
}
</script>

<style scoped>

</style>
